<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfDhetf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfDhetf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfDhetf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfDhetf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPfDhetf\App_KernelDevDebugContainer([
    'container.build_hash' => 'PfDhetf',
    'container.build_id' => '8d906f1d',
    'container.build_time' => 1613136273,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfDhetf');
